
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/sonic_shelf_db?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true

mybatis:

  mapper-locations: classpath:mapper/*.xml
  configuration:

    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

jwt:
  secret: "ThisIsASecretKeyThatIsLongEnoughForHS512AlgorithmItMustBeAtLeast64CharactersLong!"
  expiration: 86400000  # 24小时

  logging:
    level:
      com.zhongxin.sonicshelf: DEBUG